# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cambio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cambio(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1431, 1035)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Contenedor = QtWidgets.QWidget(Form)
        self.Contenedor.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: black; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    margin-top:20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  rgb(50, 50, 50); /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: left; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #f2f2f2; /* Gris claro al pasar el mouse */\n"
"    cursor: pointer;\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(255, 255, 255); /* Fondo blanco */\n"
"    border: none; /* Sin bordes visibles */\n"
"    padding: 4px; /* Espaciado interno entre el texto y los bordes */\n"
"    margin-right: 5px; /* Espaciado externo solo a la derecha */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"    color: black; /* Texto negro */\n"
"    text-align: left; /* Texto alineado a la izquierda */\n"
"    font-size: 18px; /* Tamaño del texto */\n"
"}\n"
"\n"
"/* Cuando el QLineEdit está enfocado (se está escribiendo) */\n"
"QLineEdit:focus {\n"
"    background-color: rgb(230, 230, 250); /* Color de fondo cuando el campo está activo */\n"
"    border: 1px solid rgb(0, 0, 0); /* Borde negro al estar activo */\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 20px; /* Tamaño de fuente */\n"
"    color:  black; /* Color del texto */\n"
"    margin-right: 10px; /* Espaciado a la derecha */\n"
"    padding: 5px; /* Espaciado interno */\n"
"    text-align: left; /* Alineación del texto a la izquierda */\n"
"}\n"
"QTableWidget {\n"
"    border: none;\n"
"    background-color: #ffffff; /* Fondo blanco para la tabla */\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor de la tabla */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"    transition: background-color 0.3s ease; /* Suavizado de transición de color de fondo */\n"
"    pointer-events: none; /* Desactiva la interacción con las celdas (como editar) */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #aad4ff; /* Color azul claro para celdas seleccionadas */\n"
"    color: black; /* Texto negro para celdas seleccionadas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    border: none; \n"
"    background-color: #f2f2f2; \n"
"    font-weight: normal; /* No negritas */\n"
"    text-align: center; /* Centrado del texto en los encabezados */\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); /* Sombra suave para los encabezados */\n"
"}\n"
"\n"
"QHeaderView::section:focus {\n"
"    background-color: #f2f2f2; /* Sin color de fondo cuando está en foco */\n"
"    border: none; /* Sin borde cuando está en foco */\n"
"}\n"
"\n"
"QTableWidget::item:focus {\n"
"    border: none; /* Sin borde cuando las celdas tienen el foco */\n"
"    background-color: #f2f2f2; /* Mantener el fondo sin color azul */\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f2f2f2; \n"
"    border: none; \n"
"}\n"
"\n"
"QTableWidget::verticalHeader {\n"
"    background-color: #f2f2f2;\n"
"    border: none;\n"
"    font-weight: normal; /* No negritas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #e6e6e6; /* Color de fondo al pasar el cursor sobre las celdas */\n"
"}\n"
"\n"
"/* Personalización de la barra de desplazamiento */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    width: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-height: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
"    height: 0px; /* Sin altura para los botones */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #f7f7f7; /* Fondo de la barra */\n"
"    height: 8px; /* Barra más delgada */\n"
"    border-radius: 4px; /* Bordes más redondeados */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #bbb; /* Fondo del control deslizante */\n"
"    min-width: 20px; /* Control deslizante más delgado */\n"
"    border-radius: 4px; /* Bordes redondeados */\n"
"    transition: background-color 0.3s ease; /* Transición suave para el cambio de color */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #888; /* Color más oscuro cuando el control deslizante está siendo desplazado */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #f2f2f2; /* Fondo para los botones de la barra */\n"
"    width: 0px; /* Sin ancho para los botones */\n"
"}\n"
"\n"
"\n"
"")
        self.Contenedor.setObjectName("Contenedor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenedor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Contenido = QtWidgets.QStackedWidget(self.Contenedor)
        self.Contenido.setStyleSheet("margin-left:10px;\n"
"border-radius:15px;\n"
"background-color: #f2f2f2; \n"
"")
        self.Contenido.setObjectName("Contenido")
        self.ContenidoPage1 = QtWidgets.QWidget()
        self.ContenidoPage1.setObjectName("ContenidoPage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ContenidoPage1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.InputPrecioDevuelto = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPrecioDevuelto.sizePolicy().hasHeightForWidth())
        self.InputPrecioDevuelto.setSizePolicy(sizePolicy)
        self.InputPrecioDevuelto.setMinimumSize(QtCore.QSize(250, 50))
        self.InputPrecioDevuelto.setMaximumSize(QtCore.QSize(250, 50))
        self.InputPrecioDevuelto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputPrecioDevuelto.setObjectName("InputPrecioDevuelto")
        self.gridLayout_2.addWidget(self.InputPrecioDevuelto, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.SpinCambio = QtWidgets.QSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinCambio.sizePolicy().hasHeightForWidth())
        self.SpinCambio.setSizePolicy(sizePolicy)
        self.SpinCambio.setMinimumSize(QtCore.QSize(250, 50))
        self.SpinCambio.setMaximumSize(QtCore.QSize(250, 50))
        self.SpinCambio.setStyleSheet("QSpinBox {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border: none; /* Sin borde */\n"
"    color: black; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    height: 40px; /* Altura del spinbox */\n"
"}\n"
"\n"
"/* Flechas de incremento/decremento */\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: transparent; /* Fondo transparente */\n"
"    border: none; /* Sin borde */\n"
"    width: 20px; /* Tamaño del botón */\n"
"}\n"
"\n"
"/* Ocultar las flechas si no las quieres visibles */\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"    image: none; /* Elimina la flecha */\n"
"}\n"
"\n"
"/* Hover para el campo */\n"
"QSpinBox:hover {\n"
"    cursor: pointer; /* Cursor de mano */\n"
"}\n"
"")
        self.SpinCambio.setObjectName("SpinCambio")
        self.gridLayout_2.addWidget(self.SpinCambio, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.InputPrecioCambio = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputPrecioCambio.sizePolicy().hasHeightForWidth())
        self.InputPrecioCambio.setSizePolicy(sizePolicy)
        self.InputPrecioCambio.setMinimumSize(QtCore.QSize(250, 50))
        self.InputPrecioCambio.setMaximumSize(QtCore.QSize(250, 50))
        self.InputPrecioCambio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputPrecioCambio.setObjectName("InputPrecioCambio")
        self.gridLayout_2.addWidget(self.InputPrecioCambio, 7, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.InputCambio = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputCambio.sizePolicy().hasHeightForWidth())
        self.InputCambio.setSizePolicy(sizePolicy)
        self.InputCambio.setMinimumSize(QtCore.QSize(250, 50))
        self.InputCambio.setMaximumSize(QtCore.QSize(250, 50))
        self.InputCambio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputCambio.setObjectName("InputCambio")
        self.gridLayout_2.addWidget(self.InputCambio, 5, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.InputDevuelto = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputDevuelto.sizePolicy().hasHeightForWidth())
        self.InputDevuelto.setSizePolicy(sizePolicy)
        self.InputDevuelto.setMinimumSize(QtCore.QSize(250, 50))
        self.InputDevuelto.setMaximumSize(QtCore.QSize(250, 50))
        self.InputDevuelto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputDevuelto.setObjectName("InputDevuelto")
        self.gridLayout_2.addWidget(self.InputDevuelto, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_3)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 0, 1, 1)
        self.SpinDevuelto = QtWidgets.QSpinBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinDevuelto.sizePolicy().hasHeightForWidth())
        self.SpinDevuelto.setSizePolicy(sizePolicy)
        self.SpinDevuelto.setMinimumSize(QtCore.QSize(250, 50))
        self.SpinDevuelto.setMaximumSize(QtCore.QSize(250, 50))
        self.SpinDevuelto.setStyleSheet("QSpinBox {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border: none; /* Sin borde */\n"
"    color: black; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    height: 40px; /* Altura del spinbox */\n"
"}\n"
"\n"
"/* Flechas de incremento/decremento */\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    background-color: transparent; /* Fondo transparente */\n"
"    border: none; /* Sin borde */\n"
"    width: 20px; /* Tamaño del botón */\n"
"}\n"
"\n"
"/* Ocultar las flechas si no las quieres visibles */\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"    image: none; /* Elimina la flecha */\n"
"}\n"
"\n"
"/* Hover para el campo */\n"
"QSpinBox:hover {\n"
"    cursor: pointer; /* Cursor de mano */\n"
"}\n"
"")
        self.SpinDevuelto.setObjectName("SpinDevuelto")
        self.gridLayout_2.addWidget(self.SpinDevuelto, 3, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.ComboPrecios = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboPrecios.sizePolicy().hasHeightForWidth())
        self.ComboPrecios.setSizePolicy(sizePolicy)
        self.ComboPrecios.setMinimumSize(QtCore.QSize(250, 50))
        self.ComboPrecios.setMaximumSize(QtCore.QSize(250, 50))
        self.ComboPrecios.setStyleSheet("QComboBox {\n"
"    background-color: white; /* Fondo blanco */\n"
"    border: none; /* Sin borde */\n"
"    color: black; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes redondeados */\n"
"    padding: 5px 10px; /* Espaciado interno */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    height: 40px; /* Altura del combo box */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: transparent; /* Fondo transparente */\n"
"    border: none; /* Sin borde */\n"
"    width: 20px; /* Tamaño del botón */\n"
"    /* No se define la flecha, por lo que se elimina */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    cursor: pointer; /* Cursor de mano */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white; /* Fondo del menú desplegable */\n"
"    border: none; /* Sin borde */\n"
"    color: black; /* Color del texto en las opciones */\n"
"    selection-background-color: rgb(106, 106, 106); /* Fondo gris claro al seleccionar */\n"
"    selection-color: white; /* Texto blanco al seleccionar */\n"
"    border-radius: 10px; /* Bordes redondeados */\n"
"}\n"
"\n"
"")
        self.ComboPrecios.setObjectName("ComboPrecios")
        self.gridLayout_2.addWidget(self.ComboPrecios, 4, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.LabelVentasA = QtWidgets.QLabel(self.widget_3)
        self.LabelVentasA.setStyleSheet("#LabelVentasA {\n"
"    font-weight: bold; /* Negrita */\n"
"    font-size: 34px; /* Tamaño de fuente */\n"
"}\n"
"")
        self.LabelVentasA.setObjectName("LabelVentasA")
        self.gridLayout_2.addWidget(self.LabelVentasA, 0, 0, 1, 2)
        self.InputDiferencia = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputDiferencia.sizePolicy().hasHeightForWidth())
        self.InputDiferencia.setSizePolicy(sizePolicy)
        self.InputDiferencia.setMinimumSize(QtCore.QSize(250, 50))
        self.InputDiferencia.setMaximumSize(QtCore.QSize(250, 50))
        self.InputDiferencia.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.InputDiferencia.setObjectName("InputDiferencia")
        self.gridLayout_2.addWidget(self.InputDiferencia, 8, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.BtnCambio = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnCambio.sizePolicy().hasHeightForWidth())
        self.BtnCambio.setSizePolicy(sizePolicy)
        self.BtnCambio.setMinimumSize(QtCore.QSize(500, 50))
        self.BtnCambio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnCambio.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: red\n"
"; /* Fondo blanco */\n"
"    border: none; /* Sin borde ni decoración inicial */\n"
"    color:  white; /* Color del texto */\n"
"    border-radius: 15px; /* Bordes circulares */\n"
"    padding: 5px 10px; /* Espaciado interno para mejor apariencia */\n"
"    height: 40px; /* Altura del botón */\n"
"    text-align: center; /* Alinea el texto del botón a la izquierda */\n"
"    font-size: 18px; /* Tamaño de fuente */\n"
"    margin-top:20px;\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(106, 106, 106); /* Gris claro al pasar el mouse */\n"
"    cursor: pointer; /* Cursor de mano al pasar sobre el botón */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/iconos/editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnCambio.setIcon(icon)
        self.BtnCambio.setIconSize(QtCore.QSize(30, 30))
        self.BtnCambio.setObjectName("BtnCambio")
        self.gridLayout.addWidget(self.BtnCambio, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignHCenter)
        self.widget_2 = QtWidgets.QWidget(self.ContenidoPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(1200, 0))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        self.widget = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.ContenidoPage1)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Contenido.addWidget(self.ContenidoPage1)
        self.horizontalLayout_2.addWidget(self.Contenido)
        self.horizontalLayout.addWidget(self.Contenedor)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Cantidad:"))
        self.label.setText(_translate("Form", "Producto de Cambio:"))
        self.label_2.setText(_translate("Form", "Cantidad:"))
        self.label_4.setText(_translate("Form", "Precio:"))
        self.label_7.setText(_translate("Form", "Elije el Precio:"))
        self.label_3.setText(_translate("Form", "Producto devuelto:"))
        self.LabelVentasA.setText(_translate("Form", "Devoluciones"))
        self.label_6.setText(_translate("Form", "Diferencia de Precios:"))
        self.BtnCambio.setText(_translate("Form", "Hacer Intercambio"))
